apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: restapi-delete
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 1
      MinScale: 0
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  package:
    functionName: MessageDeleteHandler
    packageref:
      name: restapi-go-pkg
      namespace: default
      resourceversion: "133729"
  resources: {}
  secrets: null
