apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
  labels:
    name: guestbook

---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: guestbook
spec:
  selector:
    name:  cockroachdb
    service: database
  type:  ClusterIP
  ports:
  - name: db
    port: 26257
    targetPort:  26257
  - name: dashboard
    port: 8080
    targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  cockroachdb
  namespace: guestbook
  labels:
    service: database
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  cockroachdb
        service: database
    spec:
      containers:
      - name:  db
        image:  cockroachdb/cockroach:v2.0.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        command:
          - "/cockroach/cockroach"
          - "start"
          - "--insecure"
      restartPolicy: Always
