apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: account-login
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  package:
    functionName: AccountLoginHandler
    packageref:
      name: bank-go-pkg
      namespace: default
      resourceversion: "9345"
  resources: {}
  secrets: null
