apiVersion: fission.io/v1
kind: Package
metadata:
  name: bank-go-pkg
  namespace: default
spec:
  source:
    url: archive://bank-go-zip
  buildcmd: "build"
  environment:
    name: go
    namespace: default
status:
  buildstatus: pending

---
kind: ArchiveUploadSpec
name: bank-go-zip
include:
  - "functions/*.go"
  - "functions/vendor"

---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: web-pkg
  namespace: default
spec:
  deployment:
    url: archive://web-pkg-zip
  buildcmd: "build"
  environment:
    name: python
    namespace: default
status:
  buildstatus: succeeded

---
kind: ArchiveUploadSpec
name: web-pkg-zip
include:
  - "web/*"
